### ISSUE TITLE
Exception on basal profile conversion

### ISSUE THREAD

**Issue by jotomo** [jotomo/AndroidAPS#13]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
       at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.convertProfileToComboProfile(ComboPlugin.java:297)
       at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.isThisProfileSet(ComboPlugin.java:290)
       at info.nightscout.androidaps.queue.CommandQueue.isThisProfileSet(CommandQueue.java:404)
       at info.nightscout.androidaps.queue.CommandQueue.setProfile(CommandQueue.java:310)
       at info.nightscout.androidaps.plugins.Careportal.Dialogs.NewNSTreatmentDialog.doProfileSwitch(NewNSTreatmentDialog.java:714)
       at info.nightscout.androidaps.plugins.Careportal.Dialogs.NewNSTreatmentDialog$7.onClick(NewNSTreatmentDialog.java:663)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6186)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by jotomo** [comment]
Originated from an obsolete dev build.
